name: release

on:
  push:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:

    - name: generate tags
      run: echo "::set-output name=tags::gairadzi/${{ github.event.repository.name }}:${REF_NAME:1},gairadzi/${{ github.event.repository.name }}:latest"
      #run: echo "::set-output name=tags::rebooto/vaxiin-server:${REF_NAME:1},rebooto/vaxiin-server:latest"
      id: gen_tags
      env:
        REF_NAME: ${{ github.ref_name }}

    - name: test
      run: echo ${{ steps.gen_tags.outputs.tags }}
