name: release

on:
  push:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: replace in file
      run: sed -i'' -e 's?there?${{ github.ref_name }}?' hello

    - name: list files
      run: ls

    - name: show file
      run: cat hello

  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: replace in file
      run: gsed 's?there?${{ github.ref_name }}?' hello

    - name: list files
      run: ls

    - name: show file
      run: cat hello
