name: Mosko
on:
  workflow_dispatch:
    inputs:
      deploy_opt:
        description: Deployment options
        required: true
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v4

    - name: Set commit status as pending
      uses: myrotvorets/set-commit-status-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: pending
        context: Mosko
        sha: ${{ github.sha }}

    - name: Check if dbt files changed
      id: changed-dbt-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          dbt/**

    - name: Set final commit status if no files changed
      uses: myrotvorets/set-commit-status-action@master
      if: ${{ !steps.changed-dbt-files.outputs.any_changed }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        context: Mosko
        status: ${{ job.status }}
        sha: ${{ github.sha }}

    - name: trigger test if files changed
      if: ${{ steps.changed-dbt-files.outputs.any_changed }}
      run: echo "I need to trigger tests!!!"
