name: Mosko
on:
  workflow_dispatch:
    inputs:
      deploy_opt:
        description: Deployment options
        required: true
jobs:
  run-test:
    runs-on: ubuntu-latest
    - name: Run the action # You would run your tests before this using the output to set state/desc
      uses: mapbox/create-status-check@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'Test run'
        description: 'Passed'
        state: 'success'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
