name: Mosko
on:
  workflow_dispatch:
    inputs:
      deploy_opt:
        description: Deployment options
        required: true
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set commit status as pending
      uses: myrotvorets/set-commit-status-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: pending
        context: Mosko
        sha: ${{ github.sha }}

    - name: Do the actual work
      run: exit 0

    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@master
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        context: Mosko
        status: ${{ job.status }}
        sha: ${{ github.sha }}
