name: pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pr-job:
    name: My PR job
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2
