name: Check if tests must run
on:
  push:
  workflow_run:
    workflows: [Mosko]
    types:
      - completed
jobs:
  check-for-test:
    runs-on: ubuntu-latest
    steps:
      - uses: autotelic/action-wait-for-status-check@v1
        id: wait-for-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "Mosko"
          timeoutSeconds: 5

      - name: fail if not success
        if: steps.wait-for-status.outputs.state != 'success'
        run: exit 1
